apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: mongo 
  annotations: 
    cloud.google.com/load-balancer-type: Internal
spec: 
  type: LoadBalancer
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 27017
